# Generated by Django 3.0.8 on 2020-08-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='gender_filter',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='grade_filter',
        ),
        migrations.AddField(
            model_name='survey',
            name='gender_filter1',
            field=models.CharField(default='x', max_length=10),
        ),
        migrations.AddField(
            model_name='survey',
            name='gender_filter2',
            field=models.CharField(default='y', max_length=10),
        ),
        migrations.AddField(
            model_name='survey',
            name='grade_filter1',
            field=models.IntegerField(default=5, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='grade_filter2',
            field=models.IntegerField(default=6, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='grade_filter3',
            field=models.IntegerField(default=7, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='grade_filter4',
            field=models.IntegerField(default=8, null=True),
        ),
    ]
