# Generated by Django 3.0.8 on 2020-08-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200807_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='gender_filter',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='grade_filter',
            field=models.IntegerField(null=True),
        ),
    ]
