# Generated by Django 3.0.8 on 2020-08-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200808_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='gender_filter',
            field=models.CharField(default='x', max_length=10),
        ),
        migrations.AlterField(
            model_name='survey',
            name='grade_filter',
            field=models.IntegerField(default=5, null=True),
        ),
    ]
