# Generated by Django 3.0.8 on 2020-08-28 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='changedpoint',
            new_name='changed_point',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='chargedpoint',
            new_name='charged_point',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='gainedpoint',
            new_name='gained_point',
        ),
    ]
