# Generated by Django 3.0.8 on 2020-08-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200801_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='point',
            field=models.IntegerField(default=1000),
        ),
    ]
