# Generated by Django 3.0.8 on 2020-08-28 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200828_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='gained_point',
            new_name='gainedpoint',
        ),
    ]
