# Generated by Django 3.0.8 on 2020-08-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='changedpoint',
            field=models.IntegerField(default=0),
        ),
    ]
