# Generated by Django 3.0.8 on 2020-08-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_changedpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chargedpoint',
            field=models.IntegerField(default=0),
        ),
    ]
