# Generated by Django 3.0.8 on 2020-08-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_chargedpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gainedpoint',
            field=models.IntegerField(default=0),
        ),
    ]
